package cs2

weapon_name :: proc (item_index: u16) -> string {
	switch item_index {
	case 1:   return "Deagle"
	case 2:   return "Dual Berettas"
	case 3:   return "Five-Seven"
	case 4:   return "Glock-18"
	case 7:   return "AK-47"
	case 8:   return "AUG"
	case 9:   return "AWP"
	case 10:  return "FAMAS"
	case 11:  return "G3SG1"
	case 13:  return "Galil AR"
	case 14:  return "M249"
	case 16:  return "M4A1"
	case 17:  return "MAC-10"
	case 19:  return "P90"
	case 20:  return "zone_repulsor"
	case 23:  return "MP5-SD"
	case 24:  return "UMP-45"
	case 25:  return "XM1014"
	case 26:  return "PP-Bizon"
	case 27:  return "MAG-7"
	case 28:  return "Negev"
	case 29:  return "Sawed-Off"
	case 30:  return "Tec-9"
	case 31:  return "Zeus x27"
	case 32:  return "P2000"
	case 33:  return "MP7"
	case 34:  return "MP9"
	case 35:  return "Nova"
	case 36:  return "P250"
	case 37:  return "shield"
	case 38:  return "SCAR-20"
	case 39:  return "SG 556"
	case 40:  return "SSG 08"
	case 41:  return "knifegg"
	case 42:  return "Knife"
	case 43:  return "Flashbang"
	case 44:  return "HE Grenade"
	case 45:  return "Smoke Grenade"
	case 46:  return "Molotov"
	case 47:  return "Decoy"
	case 48:  return "Incendiary Grenade"
	case 49:  return "C4"
	case 50:  return "Kevlar"
	case 51:  return "Kevlar with helmet"
	case 52:  return "heavyassaultsuit"
	case 54:  return "nvg"
	case 55:  return "Defuser"
	case 56:  return "cutters"
	case 57:  return "Healthshot"
	case 59:  return "Knife"
	case 60:  return "M4A1-S"
	case 61:  return "USP-S"
	case 63:  return "CZ75A"
	case 64:  return "Revolver"
	case 68:  return "tagrenade"
	case 69:  return "Fists"
	case 70:  return "breachcharge"
	case 72:  return "tablet"
	case 74:  return "melee"
	case 75:  return "axe"
	case 76:  return "hammer"
	case 78:  return "spanner"
	case 80:  return "knife_ghost"
	case 81:  return "firebomb"
	case 82:  return "diversion"
	case 83:  return "Grenade"
	case 84:  return "snowball"
	case 85:  return "bumpmine"
	case 500: return "Bayonet"
	case 503: return "Classic Knife"
	case 505: return "Flip Knife"
	case 506: return "Gut Knife"
	case 507: return "Karambit"
	case 508: return "M9 Bayonet"
	case 509: return "Huntsman Knife"
	case 512: return "Falchion Knife"
	case 514: return "Bowie Knife"
	case 515: return "Butterfly Knife"
	case 516: return "Shadow Daggers"
	case 517: return "Paracord Knife"
	case 518: return "Survival Knife"
	case 519: return "Ursus Knife"
	case 520: return "Navaja Knife"
	case 521: return "Nomad Knife"
	case 522: return "Stiletto Knife"
	case 523: return "Talon Knife"
	case 525: return "Skeleton Knife"
	case 526: return "Kukri Knife"
	case:     return "unknown"
	}
}
